server:
  port: 8080
  tomcat:
    max-threads: 500

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/DBNAME?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: temp
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      show-sql: true
  freemarker:
    suffix: .ftl
  main:
    allow-bean-definition-overriding: true

sentry:
  dsn: https://72d4c5fad9814bf98df9295fb251044e@aem-collector.daumkakao.io/1042
